info:
  title: Sasi
  name: sasi
  version: 1.0.0
apis:
  mappingcomponents1.0.0:
    name: mappingcomponents:1.0.0
gateways:
  - datapower-api-gateway
plans:
  default-plan:
    title: Default Plan
    description: Default Plan
    approval: false
    rate-limits:
      default:
        value: 100/1hour
    apis:
      mappingcomponents1.0.0: {}
product: 1.0.0
visibility:
  view:
    enabled: true
    type: public
    tags: []
    orgs: []
  subscribe:
    enabled: true
    type: authenticated
    tags: []
    orgs: []
